[package]
description = "A bunch of debug-related functions."
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
license = "MIT"
name = "howmanysmall/debug"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.2"

[dependencies]
